- name: stop-containers
  shell: docker kill slow-service
  register: stop_result

- name: remove-containers
  shell: docker rm slow-service
  register: delete_result
  when: stop_result.changed

- name: pull
  git:
    repo: https://github.com/DanikNik/sample_slow_service
    dest: /home/ubuntu/sample_slow_service
    update: yes
    version: master
  when: delete_result.changed

- name: deploy-new-image
  shell: bash ./scripts/deploy.sh
  args:
    chdir: /home/ubuntu/sample_slow_service
#  register: deploy_result