- name: Stop existing instances
  shell: docker kill slow_service; docker rm slow-service

- name: Pull "sample_slow_service"
  git:
    repo: git@github.com:DanikNik/sample_slow_service.git
    dest: /home/ubuntu/sample_slow_service
    update: yes
    version: master

- name: Build and run new Docker image
  shell: bash deploy.sh
  args:
    cd: /home/ubuntu/sample_slow_service