{
 "title": "Highload balancing hw",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(request_latency_hist_count[10s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(nginx_http_requests_total[10s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "ART",
   "type": "graph",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(request_latency_hist_sum[10s])) by (job) / 10",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (job) (sum by(job) (irate(node_cpu_seconds_total{mode=\"user\"}[10s])))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}