global:
  scrape_interval:     3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'aws_backend1'
    static_configs:
      - targets: ['172.31.46.139:8000', '172.31.46.139:9100']

  - job_name: 'aws_backend2'
    static_configs:
      - targets: ['172.31.35.157:8000', '172.31.35.157:9100']

  - job_name: 'aws_backend3'
    static_configs:
      - targets: ['172.31.40.43:8000', '172.31.40.43:9100']

  - job_name: 'aws_backend4'
    static_configs:
      - targets: ['172.31.35.166:8000', '172.31.35.166:9100']

  - job_name: 'balancer'
    static_configs:
      - targets: ['172.31.47.210:9113']
