global:
  scrape_interval:     3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'aws_backend1'
    static_configs:
      - targets: ['172.31.37.226:8000', '172.31.37.226:9100']

  - job_name: 'aws_backend2'
    static_configs:
      - targets: ['172.31.33.221:8000', '172.31.33.221:9100']

  - job_name: 'aws_backend3'
    static_configs:
      - targets: ['172.31.36.163:8000', '172.31.36.163:9100']

  - job_name: 'aws_backend4'
    static_configs:
      - targets: ['172.31.43.97:8000', '172.31.43.97:9100']

  - job_name: 'balancer'
    static_configs:
      - targets: ['172.31.42.182:9113']
